# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book_route.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62ook_route.proto\x12\x06mybook\"\x1b\n\x0bRequestData\x12\x0c\n\x04name\x18\x01 \x01(\t\"3\n\x04\x42ook\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61uther\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\x32;\n\x0b\x42ookService\x12,\n\x05\x63heck\x12\x13.mybook.RequestData\x1a\x0c.mybook.Book\"\x00\x42\x03\x80\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_route_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\200\001\001'
  _globals['_REQUESTDATA']._serialized_start=28
  _globals['_REQUESTDATA']._serialized_end=55
  _globals['_BOOK']._serialized_start=57
  _globals['_BOOK']._serialized_end=108
  _globals['_BOOKSERVICE']._serialized_start=110
  _globals['_BOOKSERVICE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
